name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install -y jq

      - name: Build release 5.0-6.2
        run: |
          version=${GITHUB_REF##*/}
          jq -i ".manifest_version = 1" manifest.json
          jq -i ".version = \"${version}\"" manifest.json
          echo "creating file v${version}-zabbix-5.0-6.2.zip"
          zip -r "v${version}-zabbix-5.0-6.2.zip" public Module.php manifest.json

      - name: Build release 6.4-7.0
        run: |
          version=${GITHUB_REF##*/}
          jq -i ".manifest_version = 2" manifest.json
          jq -i ".version = \"${version}\"" manifest.json
          echo "creating file v${version}-zabbix-6.4-7.0.zip"
          zip -r "v${version}-zabbix-6.4-7.0.zip" assets Module.php manifest.json

      - name: Generate release notes
        id: releasenotes
        run: ./github/release-notes.sh > RELEASE.md

      - name: Upload release artifacts
        uses: ncipollo/release-action@v1
        with:
          draft: true
          tag: 1.1.1
          bodyFile: RELEASE.md
          artifacts: "*-zabbix-6.4-7.0.zip,*-zabbix-5.0-6.2.zip"
