name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build release 5.0-6.2
        run: |
          jq '.manifest_version = 1' manifest.json > manifest.json
          zip -r "v${GITHUB_REF##*/}-zabbix-5.0-6.2.zip" public Module.php manifest.json

      - name: Build release 6.4-7.0
        run: |
          jq '.manifest_version = 2' manifest.json > manifest.json
          zip -r "v${GITHUB_REF##*/}-zabbix-6.4-7.0.zip" assets Module.php manifest.json

      - name: Generate release notes
        id: releasenotes
        run: |
          echo "notes=$(git log --oneline $(git tag |tail -1)..)" >> $GITHUB_ENV
          echo "done."

      - name: Upload release artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: 1.1.1
          allowUpdates: true
          generateReleaseNotes: true
          artifacts: "v${GITHUB_REF##*/}-zabbix-6.4-7.0.zip,v${GITHUB_REF##*/}-zabbix-5.0-6.2.zip"
