name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build release 5.0-6.2
        run: |
          jq '.manifest_version = 1' manifest.json > manifest.json
          echo "creating file v${GITHUB_REF##*/}-zabbix-5.0-6.2.zip"
          zip -r "v${GITHUB_REF##*/}-zabbix-5.0-6.2.zip" public Module.php manifest.json

      - name: Build release 6.4-7.0
        run: |
          jq '.manifest_version = 2' manifest.json > manifest.json
          echo "creating file v${GITHUB_REF##*/}-zabbix-6.4-7.0.zip"
          zip -r "v${GITHUB_REF##*/}-zabbix-6.4-7.0.zip" assets Module.php manifest.json

      - name: Generate release notes
        id: releasenotes
        run: |
          latest_tag=$(git describe --abbrev=0 --tags 2>/dev/null || echo "none")

          if [ "$latest_tag" != "none" ]; then
            commits=$(git log --oneline $latest_tag..)
            echo "notes=$commits" >> $GITHUB_ENV
          else
            echo "No tags found, skipping release notes generation."
            echo "notes=" >> $GITHUB_ENV
          fi

      - name: Upload release artifacts
        uses: ncipollo/release-action@v1
        with:
          tag: ${GITHUB_REF##*/}
          generateReleaseNotes: true
          artifacts: "v${GITHUB_REF##*/}-zabbix-6.4-7.0.zip,v${GITHUB_REF##*/}-zabbix-5.0-6.2.zip"
